-- ============================================
-- Gravity-DBMS: Seed Data  
-- Run this AFTER schema.sql in Supabase SQL Editor
-- Embeddings will be generated by the app
-- ============================================

INSERT INTO documents (title, content, category, metadata) VALUES

-- === STUDENTS (Engineering) ===
('Ram Sharma', 'Ram Sharma is a computer science student in Class 12-A. He excels in mathematics and programming. His favorite subjects are data structures and algorithms. He scored 95 in his last exam.', 'Engineering', '{"type": "student", "class": "12-A", "marks": 95, "subjects": ["CS", "Math"]}'),

('Priya Patel', 'Priya Patel is an electronics engineering student in Class 11-B. She is passionate about robotics and circuit design. She leads the school robotics club and won the state competition.', 'Engineering', '{"type": "student", "class": "11-B", "marks": 88, "subjects": ["Electronics", "Physics"]}'),

('Arjun Verma', 'Arjun Verma is a mechanical engineering student in Class 12-B. He loves 3D modeling and CAD design. He is building a solar-powered drone for his final year project.', 'Engineering', '{"type": "student", "class": "12-B", "marks": 82, "subjects": ["Mechanical", "CAD"]}'),

('Sneha Iyer', 'Sneha Iyer is a software engineering student in Class 11-A. She is a full-stack developer who builds web apps using React and Node.js. She contributes to open source projects on GitHub.', 'Engineering', '{"type": "student", "class": "11-A", "marks": 91, "subjects": ["CS", "Web Dev"]}'),

('Vikram Singh', 'Vikram Singh is an AI and machine learning enthusiast in Class 12-A. He has published a research paper on neural networks. He scored perfect marks in his deep learning course.', 'Engineering', '{"type": "student", "class": "12-A", "marks": 98, "subjects": ["AI", "ML", "Math"]}'),

-- === STUDENTS (Marketing) ===
('Ananya Gupta', 'Ananya Gupta is a marketing student in Class 11-C. She runs social media campaigns for local businesses. Her Instagram marketing strategies have helped clients grow by 300%.', 'Marketing', '{"type": "student", "class": "11-C", "marks": 87, "subjects": ["Marketing", "Business"]}'),

('Rohan Mehta', 'Rohan Mehta is a business administration student in Class 12-C. He organized the annual marketing festival. He specializes in digital advertising and brand strategy.', 'Marketing', '{"type": "student", "class": "12-C", "marks": 79, "subjects": ["Marketing", "Management"]}'),

('Kavya Reddy', 'Kavya Reddy is a communications student in Class 11-C. She excels in content writing and SEO optimization. She manages the school newsletter and blog.', 'Marketing', '{"type": "student", "class": "11-C", "marks": 85, "subjects": ["Content", "SEO"]}'),

-- === STUDENTS (Design) ===
('Aditya Kumar', 'Aditya Kumar is a graphic design student in Class 12-D. He creates stunning visual identities and logos. He won first place in the national design competition.', 'Design', '{"type": "student", "class": "12-D", "marks": 90, "subjects": ["Design", "Art"]}'),

('Meera Joshi', 'Meera Joshi is a UX/UI design student in Class 11-D. She designs beautiful mobile app interfaces. Her portfolio includes work for three startup companies.', 'Design', '{"type": "student", "class": "11-D", "marks": 93, "subjects": ["UX", "UI", "Design"]}'),

('Rahul Nair', 'Rahul Nair is a motion graphics student in Class 12-D. He creates cinematic animations and visual effects. He interned at a Bollywood VFX studio last summer.', 'Design', '{"type": "student", "class": "12-D", "marks": 86, "subjects": ["Animation", "VFX"]}'),

-- === COURSES ===
('Introduction to Algorithms', 'A foundational course covering sorting, searching, graph theory, dynamic programming, and computational complexity. Students learn to analyze algorithm efficiency using Big-O notation.', 'Engineering', '{"type": "course", "department": "Computer Science", "credits": 4, "difficulty": "Intermediate"}'),

('Machine Learning Fundamentals', 'Covers supervised and unsupervised learning, neural networks, decision trees, and model evaluation. Includes hands-on projects with TensorFlow and PyTorch.', 'Engineering', '{"type": "course", "department": "AI & ML", "credits": 4, "difficulty": "Advanced"}'),

('Digital Marketing Strategy', 'Learn modern marketing techniques including SEO, social media marketing, email campaigns, analytics, and conversion optimization for digital businesses.', 'Marketing', '{"type": "course", "department": "Marketing", "credits": 3, "difficulty": "Beginner"}'),

('Brand Identity Design', 'Master the art of creating compelling brand identities including logo design, typography, color theory, and visual systems for modern companies.', 'Design', '{"type": "course", "department": "Design", "credits": 3, "difficulty": "Intermediate"}'),

('Database Management Systems', 'Comprehensive course on RDBMS, SQL, normalization, indexing, transactions, and modern databases including NoSQL and vector databases like pgvector.', 'Engineering', '{"type": "course", "department": "Computer Science", "credits": 4, "difficulty": "Intermediate"}'),

('Data Visualization and Analytics', 'Learn to transform raw data into compelling visual stories using tools like D3.js, Tableau, and Python matplotlib. Covers statistical analysis and dashboard design.', 'Design', '{"type": "course", "department": "Data Science", "credits": 3, "difficulty": "Intermediate"}'),

-- === FACULTY ===
('Dr. Rajesh Kumar', 'Dr. Rajesh Kumar is a professor of computer science specializing in artificial intelligence and natural language processing. He has 20 years of teaching experience and has published over 50 research papers.', 'Engineering', '{"type": "faculty", "department": "Computer Science", "specialization": "AI/NLP", "experience": 20}'),

('Prof. Sunita Sharma', 'Prof. Sunita Sharma teaches digital marketing and consumer behavior. She previously worked as Head of Marketing at a Fortune 500 company. She mentors startup founders.', 'Marketing', '{"type": "faculty", "department": "Marketing", "specialization": "Digital Marketing", "experience": 15}'),

('Prof. Amit Desai', 'Prof. Amit Desai is a design faculty member specializing in human-computer interaction and user experience research. He has designed interfaces for major tech companies.', 'Design', '{"type": "faculty", "department": "Design", "specialization": "HCI/UX", "experience": 12}'),

-- === RESEARCH PROJECTS ===
('Smart Campus IoT Network', 'A research project to build an IoT sensor network across the campus for monitoring energy consumption, air quality, and occupancy. Uses Arduino and Raspberry Pi.', 'Engineering', '{"type": "project", "status": "Active", "team_size": 5, "budget": 50000}'),

('Social Media Sentiment Analyzer', 'Building an NLP-powered tool that analyzes social media posts to determine public sentiment about brands and products. Uses BERT and transformer models.', 'Marketing', '{"type": "project", "status": "Active", "team_size": 3, "budget": 25000}'),

('Accessible Design Toolkit', 'Creating an open-source toolkit for designers to check and improve accessibility in their designs. Includes color contrast checkers, screen reader simulators, and WCAG validators.', 'Design', '{"type": "project", "status": "Planning", "team_size": 4, "budget": 30000}');
